### ISSUE TITLE
Can we run this on Windows?

### ISSUE THREAD

**Issue by schumi2004** [hSaria/ChromaTerm#54]
I have compiled and got ct running in Windows using cygwin but how can i pipe it using Putty?

**Comment by hSaria** [comment]
Hey mate,

Unfortunately, I couldn't find a nice solution to this problem. I can think of workarounds but not solutions. In theory, you can SSH to your local computer (if it's running an SSH server) and run a remote command which would be `ssh destination | ct` which would make the output colorized and would be correctly processed by Putty, but again, this is just another workaround.

Sorry I couldn't adopt CT for Windows CMD and PowerShell. If you were to use a native xterm-256 shell and call `plink | ct` as I've mentioned before, that would work.

**Comment by Enf0** [comment]
Sorry to re-open an old issue, but I'm facing a similar challenge - I'd like to leverage Windows 10's built-in OpenSSH client (ssh.exe) together with a xterm-256 (or 24-bit true color) compatible terminal (which I believe Windows Terminal is?), and hopefully be able to pipe this input into ChromaTerm.

Would something like this be possible? It seems that 256+ color support was added to Windows 10 some time ago, unless I'm misunderstanding something?

**Comment by hSaria** [comment]
The color support in the command prompt of Windows 10 is indeed functional, so that's not a problem.

The main issue is that [`select`](https://docs.python.org/3/library/select.html#select.select) only accepts sockets on Windows; attempting to `select` from `stdin` raises an exception. I need to use `select` to support interactive applications, like SSH. Without it, the output would line-buffer.

Also, the `SIGUSR1` [signal](https://docs.python.org/3/library/signal.html) is used for reloading the config (i.e. `ct --reload`). In Windows, that signal isn't available. This isn't too big of a deal as I'm okay with disabling this feature of Windows.

**Comment by Enf0** [comment]
That makes sense. Thank you for your explanation! I'll keep using WSL for now.

**Comment by eugenov** [comment]
Hello, @hSaria !
Some time has passed, ConPTY updated with win version. Could you check this issue once more?
Sorry for necroposting.

**Comment by hSaria** [comment]
I'll take a look to see if it's doable. Thanks for pointing it out.

**Comment by eugenov** [comment]
Great news and thank you for hard work!

**Comment by hSaria** [comment]
I've pushed a commit (d046ad34658833e3f4cec2e1b7525bf8bb841e5e) that include preliminary support for Windows. I'd appreciate some testing if anyone can spare the time. If you'd like to install the latest development build, you can do so with:
```
pip install https://github.com/hSaria/ChromaTerm/archive/main.zip
```

It's currently in the "functional" phase. I've got some more tests to write.

Things that I need to fix:
* Navigating through the command history (_i.e._ using the up and down arrow keys) doesn't work
* Resizing the screen shows output that's not intended

**Comment by eugenov** [comment]
It looks ok at first sight. Testing now.

**Comment by eugenov** [comment]
There is some troubles with encoding:
```PS C:\Users\user> ls
    Каталог: C:\Users\user
    Mode                 LastWriteTime         Length Name
    ----                 -------------         ------ ----
    d-----        23.05.2022     10:37                .pulse
    d-----        28.05.2022     11:04                .ssh```
vs
```PS C:\Users\user> ls | ct
    ???????: C:\Users\user
          Mode                 LastWriteTime         Length Name
    ----                 -------------         ------ ----
    d-----        23.05.2022     10:37                .pulse
    d-----        28.05.2022     11:04                .ssh```

**Comment by eugenov** [comment]
Copy-pasting inserts only first character of copied text.

**Comment by hSaria** [comment]
Thanks for reporting. I've done some more work on this. If you'd like to test it, you can run the same command above to update.

The encoding issue might take me a while to fix and verify as my Windows installation doesn't seem to like anything that isn't English, even without ChromaTerm.

**Comment by eugenov** [comment]
Very strange thing: Windows Terminal preview 1.14 now can handle alternate buffer - it just create another buffer for this, as I know. You can easy check this by `ssh`-ing somewhere and using vim:
- open file with vim
- scroll mouse
Results: you are unable to scroll and when you leave vim all previous output remains untouched. OK

Same Windows Terminal version, but using `ct ssh`:
- open file with vim
- scroll mouse
Results: you can scroll buffer up and see previous terminal output. When you leave vim previous output overwritten with parts of previously opened file. Not OK.
Right now `ct ssh` feels like you using pre-1.14 version of Windows Terminal.

**Comment by hSaria** [comment]
Thanks again for taking the time to test it. I can confirm I'm able to reproduce it on my side. I'll make sure to run the same tests against Window Terminal in addition to CMD and PowerShell.

**Comment by hSaria** [comment]
Regarding the encoding issue, according to a [StackOverFlow](https://stackoverflow.com/questions/64028459/unicode-characters-replaced-with-question-marks-in-the-output-stream-when-using) comment, the issue is related to piping data. This is supported by the fact that running `ct powershell -command 'echo Каталог'` works. Piping it into `ct` fails, as you noted.

Turning on UTF-8 globally (oddly, a relatively-new feature in Windows 10 that isn't even turned on by default) doesn't fix that. Running `chcp 65001` doesn't fix it either. This seems like a limitation imposed by compatibility.

**Comment by eugenov** [comment]
Well, ok. Encoding is not big deal, as after `ct ssh` every character (Cyrillic too) displays as it should. I believe this is because all-UTF-8 at target host. Local shell can live without `ct` :)
I will also try to play with encoding.
Alternate buffer handling seams to me much more important issue.

**Comment by hSaria** [comment]
I've done a bit of investigating on this and found that alternate buffer handling is being done on the pseudo-console created by ConPTY. It's converting the ANSI sequence to something that's compatible with Windows shells (_i.e._ `cmd` and PowerShell). Even worse, there's no option to turn this automatic handling off when [creating the console](https://docs.microsoft.com/en-us/windows/console/createpseudoconsole).

I wrote a script to verify this. It simply creates a ConPTY console and run a bit of python within the pseudo-console to enter the alternate buffer to 5 seconds.

```python
import ctypes
import threading
from ctypes import byref, wintypes

K32 = ctypes.windll.kernel32
K32.GetProcessHeap.restype = wintypes.HANDLE
K32.HeapAlloc.argtypes = [wintypes.HANDLE, wintypes.DWORD, ctypes.c_size_t]
K32.HeapAlloc.restype = wintypes.LPVOID


class COORD(ctypes.Structure):
    _fields_ = [('X', wintypes.SHORT), ('Y', wintypes.SHORT)]


class PROCESS_INFORMATION(ctypes.Structure):
    _fields_ = [
        ('hProcess', wintypes.HANDLE),
        ('hThread', wintypes.HANDLE),
        ('dwProcessId', wintypes.DWORD),
        ('dwThreadId', wintypes.DWORD),
    ]


class STARTUPINFO(ctypes.Structure):
    _fields_ = [
        ('cb', wintypes.DWORD),
        ('lpReserved', ctypes.c_void_p),
        ('lpDesktop', ctypes.c_void_p),
        ('lpTitle', ctypes.c_void_p),
        ('dwX', wintypes.DWORD),
        ('dwY', wintypes.DWORD),
        ('dwXSize', wintypes.DWORD),
        ('dwYSize', wintypes.DWORD),
        ('dwXCountChars', wintypes.DWORD),
        ('dwYCountChars', wintypes.DWORD),
        ('dwFillAttribute', wintypes.DWORD),
        ('dwFlags', wintypes.DWORD),
        ('wShowWindow', wintypes.WORD),
        ('cbReserved2', wintypes.WORD),
        ('lpReserved2', ctypes.c_char_p),
        ('hStdInput', wintypes.HANDLE),
        ('hStdOutput', wintypes.HANDLE),
        ('hStdError', wintypes.HANDLE),
    ]


class STARTUPINFOEX(ctypes.Structure):
    _fields_ = [('StartupInfo', STARTUPINFO),
                ('lpAttributeList', ctypes.POINTER(wintypes.LPVOID))]


def run_program(program, window_size=(80, 24)):
    # Create the pipes (the program's input and output)
    input_r, input_w = wintypes.HANDLE(), wintypes.HANDLE()
    output_r, output_w = wintypes.HANDLE(), wintypes.HANDLE()

    # Connect them (read, write)
    K32.CreatePipe(byref(input_r), byref(input_w), None, 0)
    K32.CreatePipe(byref(output_r), byref(output_w), None, 0)

    # Create the pty (connected to the pipes)
    console = wintypes.HANDLE()
    console_size = COORD(*window_size)
    K32.CreatePseudoConsole(console_size, input_r, output_w, 0, byref(console))

    # Close the handles on the program's side as the console has its own set now
    K32.CloseHandle(input_r)
    K32.CloseHandle(output_w)

    # Get the size of the thread attribute list to allocate the appropriate size
    lp_size = wintypes.LPVOID()
    K32.InitializeProcThreadAttributeList(None, 1, 0, byref(lp_size))

    # Initialize the attribute list
    startup_info_ex = STARTUPINFOEX()
    startup_info_ex.StartupInfo.cb = ctypes.sizeof(STARTUPINFOEX)
    startup_info_ex.lpAttributeList = ctypes.cast(
        K32.HeapAlloc(K32.GetProcessHeap(), 0, lp_size.value),
        ctypes.POINTER(ctypes.c_void_p))
    K32.InitializeProcThreadAttributeList(startup_info_ex.lpAttributeList, 1,
                                          0, byref(lp_size))

    # Set thread's pseudoconsole to the pty
    # PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE = 0x20016
    K32.UpdateProcThreadAttribute(startup_info_ex.lpAttributeList, 0, 0x20016,
                                  console, ctypes.sizeof(console), None, None)

    # EXTENDED_STARTUPINFO_PRESENT = 0x80000
    process_info = PROCESS_INFORMATION()
    K32.CreateProcessW(None, program, None, None, False, 0x80000, None, None,
                       byref(startup_info_ex.StartupInfo), byref(process_info))

    # Read the pseudo-console's output and print it on the main pty's stdout
    def read():
        buffer = ctypes.create_string_buffer(4096)
        count = wintypes.DWORD()

        while True:
            K32.ReadFile(output_r, buffer, len(buffer), byref(count), None)
            # Not calling .decode() here to print the actual bytes received
            if count.value:
                print(buffer.raw[:count.value])

    threading.Thread(target=read, daemon=True).start()

    # Wait for the child process then close the console
    K32.WaitForSingleObject(process_info.hThread, -1)
    K32.ClosePseudoConsole(console)


# Using `repr` to escape the ANSI code when passing it to the child process
run_program('python -c "' + ';'.join([
    'import time',
    'print({})'.format(repr('\x1b[?1049h')),  # Enter alternate buffer
    'time.sleep(5)',
    'print({})'.format(repr('\x1b[?1049l')),  # Exit alternate buffer
]) + '"')

```

The output shows that ConPTY replaces the code that switches to the alternate buffer with simple instructions to clear the screen, presumably due to the limited VT support in `cmd` and PowerShell.

```python
b'\x1b[2J\x1b[m\x1b[H\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\x1b[2;1H\x1b]0;C:\\Users\\RandomUser\\AppData\\Local\\Programs\\Python\\Python39\\python.exe\x07\x1b[?25h'
b'\x1b[25l\x1b[H\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\r\n\x1b[K\x1b[2;1H\x1b[?25h'
```

The first line is the one that emulates entering the alternate buffer. Effectively, it's clearing the screen. That's it. The second line is the line that emulate exiting the alternate buffer, and it's pretty much the same as the first one with additional codes to clear any trailing characters.

At this point, I'm thoroughly disappointed with ConPTY. I've moved the code for Windows into its own branch in case the implementation is improved. Until ConPTY is improved, I'm gonna have to continue to refer people to WSL. I'm sorry. I would've preferred to have native support without the need for additional software, but it's just not ready.

**Comment by eugenov** [comment]
Thank you for researching! Hope they improve conpty not in too distant future...

**Comment by eugenov** [comment]
Hello!
Just came across post about piping in conpty here https://stackoverflow.com/questions/69244994/how-to-use-windows-conpty-api-from-a-process-whose-output-has-been-redirected
Could it be the source of issue? Seams similar.
Thank you!
And maybe this dirty hack will help: `printf "\e[?1007h"`

**Comment by hSaria** [comment]
Thanks for looking into this.

Unfortunately, that didn’t fix the issue mentioned in my previous comment. The ConPTY API is translating the output to what it thinks is most-compatible. Even when the alternate buffer is supported by a terminal, like PowerShell or the new Microsoft Terminal, the ConPTY API assumes it isn’t and automatically translates the “enter the alternate buffer” command to new-lines to clear the screen.

The alternate scroll mode command you mentioned doesn’t affect the problem because the terminal never actually receives the “enter the alternate buffer” command from the spawned program. In the other words, it’s still in the main buffer.

Here’s how the output flows from the program to the screen:

Spawned program -> ConPTY -> ChromaTerm -> Terminal

When the spawned program writes out the “enter the alternate buffer” command, the ConPTY API converts it to new-lines. ChromaTerm never receives the actual command and neither does the terminal. You can see that happening in my previous comment.

The issue of the spawned program escaping an external pipe (i.e. if ChromaTerm’s output is redirected to a file or another program) isn’t the main concern, though it’s nice to know that it can be fixed, not that I encountered or even tested for it.

**Comment by eugenov** [comment]
If you don't mind, i'd create issue at microsoft/terminal repository, since conhost repo is also there...

**Comment by hSaria** [comment]
Honestly, I don’t think it’s a good call for anyone from Microsoft to put time into this one specific problem because it’s clear that they’re reworking significant parts of this implementation or deprecating it entirely. In this thread https://github.com/microsoft/terminal/issues/1173 is a bit of relevant discussion, but it’s not limited to that one thread; there’s another 274 regarding ConPTY and ConHost.

**Comment by eugenov** [comment]
Ok, you mentioned it there, maybe is enough for now. Thanks for your hard work!
