### ISSUE TITLE
ct -a (per pattern)

### ISSUE THREAD

**Issue by cpriest** [hSaria/ChromaTerm#60]
I can understand the need to have colliding patterns off by default, I can see a number of cases where colliding patterns would be preferred.

For example, basic types such as IP Addresses, [WARNING|ERROR], date-time strings for which you would always want them to highlight at a lower priority, but not block other more specific lines from being colored.

**Example (just the output string):**
<999>Your machine has been assigned <0f0>192.168.42.37<999> and is now available.

**Where the IP address would match:**
1. HIGHLIGHT {\d+\.\d+\.\d+\.\d+} {<0f0>} {50}
2. HIGHLIGHT {^Your machine has been assigned.+$} {<999>} {1000}

Somehow be able to mark Item 1 as "continue on match", perhaps priority of `{50+}` or something.

**Comment by hSaria** [comment]
Makes sense. As part of #58, I plan on having an optional key for each highlight rules for flags. Perhaps colliding actions would fit there.

The main problem with colliding actions is that you need to be very careful, otherwise things won't match. Consider these two rules and assume you're someone completely new to ChromaTerm--:
```
HIGHLIGHT {there} {blue} {900}
HIGHLIGHT {Hello there, World} {red} {1000}
```
Assuming colliding actions are allowed, and you run `echo "Hello there, World" | ct`. One might think that the word `there` will be colored blue while `Hello` and `, World` will be red, but nope. Only `there` would get colored in blue. Because ChromaTerm-- did the following:
1. Attempt to match `there` (better priority)
2. It will be found and hence is colored blue
3. Attempt to match `Hello there, World`
4. Fail to match because the input has been changed to `Hello <color start>there<reset>, world` (the `<special codes>` are not visible to you and me, but are seen to ChromaTerm--)

If you're careful about your matching order, then the use of colliding actions is fine, but I figured I'd rather not have people  confuse themselves with why a highlight is seemingly not working _sometimes_.

I'll keep this open for v0.4.1; once v0.4.0 is released and I have a more flexible configuration format, ChromaTerm-- will be able to support those advanced use cases without deterring beginners.

Also, I may be able to always have colliding actions enabled by having two separate buffers: one that has the `<special codes>` for printing back to the user and the original one for matching highlight rules (I tried this way back but it was a bit of a hassle; perhaps round 2 will be smoother). I'll look more into this in v0.4.1.

**Comment by cpriest** [comment]
I've worked with ANSI quite a lot, one project I have [micro-chalk](https://github.com/cpriest/micro-chalk) works through the above issues by keeping a stack of fore/back color states and works on the shortest match -> longest match.

So the above example you mentioned would be rendered as {red}Hello {blue}there{red}, World{reset}.

**Comment by hSaria** [comment]
That works even better. I'll have to start keeping the original input buffer untouched to avoid not being able to match it in the future.

**Comment by hSaria** [comment]
All rules are now colliding (I've moved it to v0.4.0 since it's already resolved). Thanks to your idea of tracking colors, it is far simpler and more logical to have the rules overlap while tracking colors. ChromaTerm doesn't actually "reset" the color anymore, but rather puts in the last tracked color in. It'll only reset if it had no idea what the first color was (i.e. on program startup).

**Comment by cpriest** [comment]
Cool, yeah that's exactly how I did it.  I start the stack with \033[m.

**Comment by hSaria** [comment]
Currently, CT tracks back to the last color code and only requires a single value to be tracked. For the time being, I’m avoiding a stack as there’s external input involved here and missing a single pop (reset) in wouldn’t be recoverable; the color would be permanently stuck in the stuck unless the input has a gratuitous reset.

Tracking the last known color code (reset or otherwise) is self-healing in that the next external color repairs a miss. I’m not anticipating any misses but as I‘m not controlling the input, I can never tell.

Thanks a lot for your help. This really made CT far more deterministic and intuitive.

**Comment by cpriest** [comment]
Glad it helped. :)

I've been looking for something like this for some time, I'm hoping to 
inline it with my shell soon so that everything is subject to highlighting.

**Comment by hSaria** [comment]
I haven't tested it too much, but you can give iTerm2's (Triggers)[https://www.iterm2.com/documentation-triggers.html] a try which is terminal-wide. You can setup a regular expression with a highlight action. I've heard there's a noticeable performance hit, but I haven't tested it.

**Comment by cpriest** [comment]
yeah, I have a terminal that already does it, it hits performance pretty hard.
