### ISSUE TITLE
.chromatermrc not being parsed

### ISSUE THREAD

**Issue by Enf0** [hSaria/ChromaTerm#78]
I cannot get Cisco highlighting to work. It seems that ChromaTerm is colorizing/highlighting my output based on the rules in .chromaterm.yml, but not the regex rules in .chromatermrc.

Is there something I am not understanding? What is the difference between these two files?

![image](https://user-images.githubusercontent.com/825808/73356239-2d433f00-429a-11ea-9378-49a53bbdb116.png)

` xxx@hostname  ~  ls -l /home/xxx/.chromaterm*`
`-rw-rw-rw- 1 xxx xxx 2547 Jan 29 09:40 /home/xxx/.chromaterm.yml`
`-rw-rw-rw- 1 xxx xxx 10667 Jan 29 12:57 /home/xxx/.chromatermrc`

I'm using the .chromatermrc from [here](https://static.notx.ml/u/.chromatermrc--).

**Comment by hSaria** [comment]
`.chromatermrc` is the configuration file for the legacy fork ChromaTerm (written in C). Since v0.4, ChromaTerm was rewritten in Python 3 and will now read `.chromaterm.yml`.

The old (custom) format was:
```
HIGHLIGHT {Hello\s+world} {cyan} {1000}
```

The new (YAML) format for a rule is:
```
- rule: Hello\s+world
  color: f#123123
```

More details on the format is available on the [main page](https://github.com/hSaria/ChromaTerm#highlight-rules).

**Comment by Enf0** [comment]
Wow, thank you for the quick response! Do you know if there is a "translated" version of the .chromatermrc Cisco highlighting for the new YAML format?

**Comment by hSaria** [comment]
The [`contrib/rules`](https://github.com/hSaria/ChromaTerm/tree/master/contrib/rules) directory in the project has some topic-specific rule (networking being one of them).

Unfortunately, because the RegEx engine was changed from `PCRE` to Python's `re`, I couldn't create an automatic migration tool for the rules. Python's `re` generally supports that same features (it even pioneered some of those that `PCRE` adopted), but some differences still exist.

With that said, I'd welcome any topic-specific PRs.

**Comment by Enf0** [comment]
Thank you very much for answering so quickly.

I have reverted to version 0.3.4 for the time being. I will have a go at translating the .chromatermrc to YAML, but my RegEx skills are not that good, unfortunately.
