### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [hSaria/ChromaTerm#89]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.6.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary chromaterm -w /tmp/ext chromaterm==0.6.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting chromaterm==0.6.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/5f6/73fa7e52370a7/chromaterm-0.6.1.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-4_uajokl/chromaterm/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-4_uajokl/chromaterm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-4_uajokl/chromaterm/pip-egg-info
         cwd: /tmp/pip-wheel-4_uajokl/chromaterm/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-4_uajokl/chromaterm/setup.py", line 12, in <module>
        with open('.github/README.md', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '.github/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by hSaria** [comment]
Thanks for pointing it out. I've never ran into that issue since I prefer wheels, but I suppose some people use sdist instead (that's why I upload both to PyPI).

I've avoided the `MANIFEST.in` file for a while as it's one more thing to maintain. For the time being, I'm gonna move `README.md` to the root of project so it'll be [included by default](https://packaging.python.org/guides/using-manifest-in/). I originally put it in the `.github` directory in an effort to reduce the visible files in the project page.

P.S. Ironically, `setup.py` has been warning me about this when I build the package for quite a while; I just never noticed it.
```
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md
```

**Comment by hSaria** [comment]
v0.6.3 published with this issue fixed. Thanks again :)

**Comment by thatch** [comment]
Confirmed, thanks!
